[workspace]
authors = ["Giordon Stark <kratsg@gmail.com>"]
channels = ["conda-forge"]
name = "af-portal"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
flask = ">=3.1.2,<4"
pyyaml = ">=6.0.3,<7"
python-kubernetes = ">=34.1.0,<35"
flask-wtf = ">=1.2.2,<2"
jinja2 = ">=3.1.6,<4"
apscheduler = ">=3.11.2,<4"
arrow = ">=1.4.0,<2"
pytest = ">=9.0.3,<10"
pytest-mock = ">=3.15.1,<4"
matplotlib = ">=3.10.9,<4"

[pypi-dependencies]
flask-qrcode = ">=3.2.0, <4"
jinja2-markdown = ">=0.0.3, <0.0.4"
