apiVersion: v1
kind: Pod
metadata:
  labels:
    notebook-id: {{notebook_id}}
    notebook-name: {{notebook_name}}
    k8s-app: jupyterlab
    owner: {{owner}}
    globus-id: {{globus_id}}
    time2delete: ttl-{{hours_remaining}}
  name: {{notebook_id}}
  namespace: {{namespace}}
spec:
  {% if gpu_request %}
  nodeSelector:
    nvidia.com/gpu.memory: "{{gpu_memory}}"
  {% else %}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: partition
            operator: NotIn
            values:
            - gpu
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
          - key: partition
            operator: In
            values:
            - login
  tolerations:
    - key: hub.jupyter.org/dedicated
      operator: "Exists"
      effect: "NoSchedule"
  {% endif %}
  containers:
  - name: {{notebook_id}}
    args:
    - /.run
    - /ML_platform_tests/SetupPrivateJupyterLab.sh
    env:
    - name: "JUPYTER_TOKEN"
      value: {{token}}
    - name: API_TOKEN
      valueFrom:
        secretKeyRef:
          name: ciconnect-creds
          key: token
    - name: OWNER
      value: {{owner}}
    - name: OWNER_UID
      value: "{{owner_uid}}"
    - name: CONNECT_GROUP
      value: atlas-af
    - name: CONNECT_GID
      value: "5741"
    image: {{image}}
    imagePullPolicy: Always
    ports:
    - containerPort: 9999
    resources:
      limits:
        cpu: {{cpu_limit}}
        memory: {{memory_limit}}
        nvidia.com/gpu: {{gpu_limit}}
      requests:
        cpu: {{cpu_request}}
        memory: {{memory_request}}
        nvidia.com/gpu: {{gpu_request}}
    volumeMounts:
      - name: nfs-home
        mountPath: /home
      - name: ceph-data
        mountPath: /data
        subPath: data
      - name: cvmfs
        mountPath: /cvmfs
        mountPropagation: HostToContainer
  restartPolicy: Always
  volumes:
    - name: nfs-home
      nfs: 
        server: nfs.af.uchicago.edu
        path: /export/home
    - name: ceph-data
      cephfs:
        monitors: 
        - 192.170.240.135:6789
        - 192.170.240.148:6789
        - 192.170.240.192:6789
        user: admin
        secretRef:
          name: ceph-secret
    - name: cvmfs
      hostPath:
        path: /cvmfs
