apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: jupyterlab
    notebook-id: {{notebook_id}}
    owner: {{owner}}
  name: {{notebook_id}}
  namespace: {{namespace}}
type: Opaque
data:
  token: {{token}}