name: Build AF frontend image

on:
  push:
    branches:
      - "main"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read # actions/checkout needs to read repository contents
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@ef432483bd0252dd948d1d11e60c96a1c93646a9 # v7.0
        with:
          image: maniaclab/af-portal
          tags: latest, ${{ github.sha }}
          registry: hub.opensciencegrid.org
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

  deploy:
    name: Trigger GitOps deployment
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.AAAS_GITOPS_DEPLOY_TRIGGER  }}
          repository: maniaclab/flux_apps
          event-type: gitops-af-app-trigger
          client-payload:
            '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
