name: Publish Analysis Facility MKDocs via GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4.2.2
        - uses: actions/setup-python@v5.3.0
          with: 
            python-version: 3.11
        - run: pip install mkdocs-material
        - run: mkdocs gh-deploy --force
